# Generated by Django 5.2.14 on 2026-05-26 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0005_add_weapon_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gender', models.CharField(blank=True, max_length=80)),
                ('alignment', models.CharField(blank=True, choices=[('lawful_good', 'Lawful Good'), ('neutral_good', 'Neutral Good'), ('chaotic_good', 'Chaotic Good'), ('lawful_neutral', 'Lawful Neutral'), ('true_neutral', 'True Neutral'), ('chaotic_neutral', 'Chaotic Neutral'), ('lawful_evil', 'Lawful Evil'), ('neutral_evil', 'Neutral Evil'), ('chaotic_evil', 'Chaotic Evil')], max_length=32)),
                ('deity', models.CharField(blank=True, max_length=120)),
                ('background', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('base_str', models.PositiveSmallIntegerField(default=8)),
                ('base_dex', models.PositiveSmallIntegerField(default=8)),
                ('base_con', models.PositiveSmallIntegerField(default=8)),
                ('base_int', models.PositiveSmallIntegerField(default=8)),
                ('base_wis', models.PositiveSmallIntegerField(default=8)),
                ('base_cha', models.PositiveSmallIntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='rules.race')),
                ('subrace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='rules.subrace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
