# Generated by Django 5.2.14 on 2026-05-26 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('rules', '0005_add_weapon_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='characters.character')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_levels', to='rules.characterclass')),
            ],
            options={
                'ordering': ['character_class__name'],
                'constraints': [models.UniqueConstraint(fields=('character', 'character_class'), name='unique_character_class_level')],
            },
        ),
    ]
