# Generated by Django 5.2.14 on 2026-05-27 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_characterclasslevel'),
        ('rules', '0005_add_weapon_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranks', models.PositiveSmallIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='characters.character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_skills', to='rules.skill')),
            ],
            options={
                'ordering': ['skill__name'],
                'constraints': [models.UniqueConstraint(fields=('character', 'skill'), name='unique_character_skill')],
            },
        ),
    ]
