# Generated by Django 5.2.14 on 2026-05-26 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section', models.CharField(blank=True, max_length=255)),
                ('source_status', models.CharField(choices=[('verified', 'Verified'), ('needs_verification', 'Needs verification'), ('conflicting', 'Conflicting')], default='needs_verification', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('creature_type', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('movement_speed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vision', models.CharField(blank=True, max_length=100)),
                ('favored_class', models.CharField(blank=True, max_length=100)),
                ('level_adjustment', models.SmallIntegerField(default=0)),
                ('attribute_modifiers', models.JSONField(blank=True, default=dict)),
                ('skill_bonuses', models.JSONField(blank=True, default=dict)),
                ('racial_features', models.JSONField(blank=True, default=list)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='rules.rulesource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrestigeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section', models.CharField(blank=True, max_length=255)),
                ('source_status', models.CharField(choices=[('verified', 'Verified'), ('needs_verification', 'Needs verification'), ('conflicting', 'Conflicting')], default='needs_verification', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hit_die', models.CharField(blank=True, max_length=10)),
                ('skill_points_per_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('class_skills', models.JSONField(blank=True, default=list)),
                ('special_progression', models.JSONField(blank=True, default=list)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='rules.rulesource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section', models.CharField(blank=True, max_length=255)),
                ('source_status', models.CharField(choices=[('verified', 'Verified'), ('needs_verification', 'Needs verification'), ('conflicting', 'Conflicting')], default='needs_verification', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('feat_type', models.CharField(blank=True, max_length=100)),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('effects', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='rules.rulesource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClericDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section', models.CharField(blank=True, max_length=255)),
                ('source_status', models.CharField(choices=[('verified', 'Verified'), ('needs_verification', 'Needs verification'), ('conflicting', 'Conflicting')], default='needs_verification', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('granted_power', models.TextField(blank=True)),
                ('domain_spells', models.JSONField(blank=True, default=dict)),
                ('allowed_deities', models.JSONField(blank=True, default=list)),
                ('alignment_restrictions', models.JSONField(blank=True, default=list)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='rules.rulesource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section', models.CharField(blank=True, max_length=255)),
                ('source_status', models.CharField(choices=[('verified', 'Verified'), ('needs_verification', 'Needs verification'), ('conflicting', 'Conflicting')], default='needs_verification', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hit_die', models.CharField(blank=True, max_length=10)),
                ('skill_points_per_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('base_attack_bonus', models.CharField(blank=True, max_length=50)),
                ('saving_throws', models.JSONField(blank=True, default=dict)),
                ('class_skills', models.JSONField(blank=True, default=list)),
                ('special_progression', models.JSONField(blank=True, default=list)),
                ('alignment_restrictions', models.JSONField(blank=True, default=list)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='rules.rulesource')),
            ],
            options={
                'verbose_name_plural': 'character classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section', models.CharField(blank=True, max_length=255)),
                ('source_status', models.CharField(choices=[('verified', 'Verified'), ('needs_verification', 'Needs verification'), ('conflicting', 'Conflicting')], default='needs_verification', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('ability', models.CharField(max_length=3)),
                ('trained_only', models.BooleanField(default=False)),
                ('armor_check_penalty', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='rules.rulesource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpellSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section', models.CharField(blank=True, max_length=255)),
                ('source_status', models.CharField(choices=[('verified', 'Verified'), ('needs_verification', 'Needs verification'), ('conflicting', 'Conflicting')], default='needs_verification', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('opposition_rules', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='rules.rulesource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section', models.CharField(blank=True, max_length=255)),
                ('source_status', models.CharField(choices=[('verified', 'Verified'), ('needs_verification', 'Needs verification'), ('conflicting', 'Conflicting')], default='needs_verification', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('levels', models.JSONField(blank=True, default=dict)),
                ('components', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='rules.rulesource')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spells', to='rules.spellschool')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section', models.CharField(blank=True, max_length=255)),
                ('source_status', models.CharField(choices=[('verified', 'Verified'), ('needs_verification', 'Needs verification'), ('conflicting', 'Conflicting')], default='needs_verification', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('attribute_modifiers', models.JSONField(blank=True, default=dict)),
                ('skill_bonuses', models.JSONField(blank=True, default=dict)),
                ('special_rules', models.JSONField(blank=True, default=list)),
                ('base_race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subraces', to='rules.race')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='rules.rulesource')),
            ],
            options={
                'ordering': ['base_race__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section', models.CharField(blank=True, max_length=255)),
                ('source_status', models.CharField(choices=[('verified', 'Verified'), ('needs_verification', 'Needs verification'), ('conflicting', 'Conflicting')], default='needs_verification', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('damage', models.CharField(blank=True, max_length=50)),
                ('critical', models.CharField(blank=True, max_length=50)),
                ('damage_type', models.CharField(blank=True, max_length=100)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='rules.rulesource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
